#ifndef ACTUATION_MSGS__MSG__DOUBLE36_IDL_
#define ACTUATION_MSGS__MSG__DOUBLE36_IDL_

module actuation_msgs {
  module msg {
    struct Double36 {
      double data[36];
    };
  };
};

#endif  // ACTUATION_MSGS__MSG__DOUBLE36_IDL_
