# Copyright (c) 2024-2025, Arm Limited.
# SPDX-License-Identifier: Apache-2.0

# The west manifest file for the actuation Zephyr app.
#
# The per-installation west configuration file, .west/config, sets the
# path to the project containing this file in the [manifest] section's
# "path" variable.

---
manifest:
  defaults:
    remote: upstream

  remotes:
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos

  #
  # Please add items below based on alphabetical order
  projects:
    - name: cmsis
      revision: 4b96cbb174678dcd3ca86e11e1f24bc5f8726da0
      path: modules/hal/cmsis
      groups:
        - hal
    - name: hal_nxp
      revision: d45b14c198d778658b7853b48378d2e132a6c4be
      path: modules/hal/hal_nxp
      groups:
        - hal
    - name: zephyr
      revision: 6aeb7a2b96c2b212a34f00c0ad3862ac19e826e8
      west-commands: scripts/west-commands.yml

  group-filter:
    - -ci

  self:
    path: actuation_autoware
